spring:
    dubbo:         application:
                name: "template-project"
                                environment: develop
        registry:
              protocol: "zookeeper"
              address: "127.0.0.1:2183"
        protocol:
              name: dubbo
              port: 20880
        scan: com.kaka.project.openservice,com.kaka.project.call
        monitor:
          protocol: registry
    datasource:
            url: 127.0.0.1
            username: root
            password: root
            # 使用druid数据源
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.jdbc.Driver
            filters: stat
            maxActive: 20
            initialSize: 1
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20

    #jpa:
    #  database: MYSQL
    #  show-sql: true
# redis
    redis:
    # Redis数据库索引（默认为0）
        database: 0
    # Redis服务器地址
        host: 127.0.0.1
    # Redis服务器连接密码（默认为空）
        password:
    # Redis服务器连接端口
        port: 6379
    # 连接超时时间（毫秒）
        timeout: 100
        pool:
    # 连接池中的最大空闲连接
          max-idle: 10
       # 连接池中的最小空闲连接
          min-idle: 10
       # 连接池最大连接数（使用负值表示没有限制）
          max-active: 10
       # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1

# token
token:
  header: Authorization
  secret: "!&WEOM48"
    expiration: 604800
    refresh-expiration: 2592000
server:
    port: 8001
    tomcat:
        uri-encoding: UTF-8


# Logging configuration
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG

mybatis:
    config-locations: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:com/kaka/project/dataobject/*.xml
    type-aliases-package: com.kaka.project.dataobject


environment:
    env-date: "2017-08-18"
    sys-version: "v170818.0.0.1"